import type { ThemeCategory } from "../types.ts";

export const PROJECT_CONTEXT = {
  primaryProject: "Volcker Copilot",
  stack: [
    "Next.js 15",
    "React 19",
    "TypeScript",
    "Tailwind",
    "Anthropic SDK",
    "evaluator pipeline",
    "Vercel deploy",
  ],
  interests: [
    "agent workflows",
    "Codex",
    "Claude",
    "skills",
    "automations",
    "evals",
    "prompting",
    "LLM reliability",
    "Next.js",
    "React",
    "TypeScript",
    "security",
    "deployment",
    "developer tooling",
    "product patterns",
  ],
} as const;

// The current source set is bilingual. Telegram curator content often mixes Russian and English,
// while GitHub and official-source content is primarily English. These keyword lists intentionally
// include both languages so one scorer can handle the current source mix without a translation step.
export const THEME_KEYWORDS: Record<ThemeCategory, string[]> = {
  "agent-workflow": [
    "agent",
    "agents",
    "workflow",
    "planner",
    "codex",
    "claude",
    "claude code",
    "skill",
    "skills",
    "agents.md",
    "claude.md",
    "memory",
    "context",
    "worktree",
    "subagent",
    "?????",
    "??????",
    "????????",
    "?????",
    "??????",
    "??????",
    "????????",
    "????????",
    "????????",
  ],
  "prompting-evals": [
    "prompt",
    "prompting",
    "eval",
    "evaluation",
    "reliability",
    "hallucination",
    "benchmark",
    "regression",
    "guardrail",
    "routing",
    "prompt anatomy",
    "text-to-sql",
    "??????",
    "?????????",
    "????",
    "?????",
    "??????????? ????",
    "????????????",
    "?????",
    "?????",
  ],
  frontend: [
    "next.js",
    "react",
    "typescript",
    "tailwind",
    "shadcn",
    "server component",
    "server action",
    "streaming",
    "client island",
    "frontend",
    "ui",
    "?????????",
    "????????",
    "?????????",
  ],
  security: [
    "security",
    "secret",
    "key",
    "token",
    "auth",
    "permission",
    "leak",
    "server-only",
    "browser bundle",
    "sandbox",
    "isolation",
    "cloudflare",
    "captcha",
    "sentry",
    "slack",
    "???????",
    "????????",
    "??????",
    "????",
    "???????",
    "????????",
  ],
  deploy: [
    "vercel",
    "deploy",
    "deployment",
    "release",
    "preview",
    "production",
    "prod",
    "rollout",
    "????",
    "?????????",
    "?????",
    "??????",
  ],
  tooling: [
    "tooling",
    "cli",
    "sdk",
    "linter",
    "testing",
    "observability",
    "github",
    "open-source",
    "opensource",
    "repo",
    "repository",
    "tool",
    "??????????",
    "???????????",
    "????????",
    "???",
    "json",
  ],
  automation: [
    "automation",
    "automations",
    "schedule",
    "scheduled",
    "cron",
    "pipeline",
    "mcp",
    "apify",
    "actor",
    "dataset",
    "webhook",
    "scraping",
    "???????????",
    "????????",
    "????????",
    "??????",
    "????????",
  ],
};

export const STACK_KEYWORDS = [
  "next.js",
  "react",
  "typescript",
  "tailwind",
  "anthropic",
  "claude",
  "claude code",
  "codex",
  "cursor",
  "apify",
  "github",
  "slack",
  "sentry",
  "vercel",
  "eval",
  "prompt",
  "agent",
  "automation",
  "skill",
  "mcp",
  "sdk",
  "?????",
  "?????",
  "???????????",
  "??????",
  "????????",
  "????????",
];

export const DIRECT_SIGNAL_KEYWORDS = [
  "codex",
  "claude code",
  "agents.md",
  "claude.md",
  "apify",
  "automations",
  "repo map",
  "repomap",
  "prompt anatomy",
  "google workspace cli",
  "symphony",
  "pm skills",
  "windows",
  "sandbox",
  "sentry",
  "cursor",
  "agent skills",
  "skills",
  "???",
  "?????",
  "???????????",
  "????????",
  "????????",
  "?????",
];

export const NOISE_KEYWORDS = [
  "giveaway",
  "subscribe",
  "invite three friends",
  "airdrop",
  "trading signal",
  "price target",
  "politics",
  "casino",
  "pump",
  "lottery",
  "??????????",
  "????????",
  "???????",
];
