import type { SkillCatalogEntry, TrustedSkillSource } from "../types.ts";

export const TRUSTED_SKILL_SOURCES: TrustedSkillSource[] = [
  {
    id: "openai-skills",
    label: "openai/skills",
    url: "https://github.com/openai/skills",
    category: "official-catalog",
    compatibility: ["codex"],
    whyTrack: "Official Codex-oriented skills and examples. Good source for capability truth and Codex-native conventions.",
    installHint: "Treat as Codex-first reference material and selective install source.",
  },
  {
    id: "anthropics-skills",
    label: "anthropics/skills",
    url: "https://github.com/anthropics/skills",
    category: "official-catalog",
    compatibility: ["claude-code"],
    whyTrack: "Official Claude Code plugin and skill ecosystem. Good source for Claude-native workflows and packaging patterns.",
    installHint: "Use for Claude Code plugin and team-skill patterns.",
  },
  {
    id: "vercel-open-skills",
    label: "vercel-labs/skills",
    url: "https://github.com/vercel-labs/skills",
    category: "community-catalog",
    compatibility: ["codex", "claude-code"],
    whyTrack: "Open agent-skills installer and ecosystem. Important because it spans both Codex and Claude Code with a shared specification.",
    installHint: "When networked installs are allowed, prefer project-local installs via npx skills add <repo> -a codex -a claude-code.",
  },
  {
    id: "skills-sh",
    label: "skills.sh",
    url: "https://skills.sh/",
    category: "marketplace",
    compatibility: ["codex", "claude-code"],
    whyTrack: "Fast discovery layer for current high-signal community skills across the open agent-skills ecosystem.",
    installHint: "Use for discovery first, then install the underlying repo selectively.",
  },
  {
    id: "obra-superpowers",
    label: "obra/superpowers",
    url: "https://github.com/obra/superpowers",
    category: "community-repo",
    compatibility: ["codex", "claude-code"],
    whyTrack: "Strong practitioner workflow pack with TDD, debugging, worktrees, planning, and parallel-agent patterns.",
    installHint: "Claude Code can install via plugin marketplace. Codex has a dedicated INSTALL flow in the repo.",
  },
  {
    id: "alenazaharovaux-share",
    label: "alenazaharovaux/share",
    url: "https://github.com/alenazaharovaux/share",
    category: "community-repo",
    compatibility: ["claude-code"],
    whyTrack: "Curated skill collection with strong frontend, UX audit, visual explainer, skill quality testing, tool discovery, and finding triage skills. Includes official Anthropic plugin adaptations and journalism-extended tooling.",
    installHint: "Cherry-pick individual skills. MIT license. Good source for website-profile, creator-profile, and skill-development skills.",
  },
  {
    id: "vercel-agent-skills",
    label: "vercel-labs/agent-skills",
    url: "https://github.com/vercel-labs/agent-skills",
    category: "community-repo",
    compatibility: ["codex", "claude-code"],
    whyTrack: "High-quality workflow and frontend-oriented skills that fit the Next.js, React, and Vercel side of our stack.",
    installHint: "Install specific skills rather than the whole repo unless a project clearly needs all of it.",
  },
];

export const SKILL_CATALOG: SkillCatalogEntry[] = [
  {
    id: "starter-pack-work-split",
    label: "Starter Pack Work Split",
    summary: "Project-owned workflow for splitting Starter Pack delivery into architecture, docs (user-facing), and backend lanes with long-leg autonomous task packets and strict project-relevance checks.",
    tags: ["starter-pack", "parallel", "architecture", "docs", "backend", "handoff"],
    recommendedWhen: ["running Codex and Claude Code in parallel", "building the standalone starter-pack track", "reducing interruption-heavy delegation"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "project-owned",
    sourceUrl: "skills/starter-pack-work-split/SKILL.md",
    evidenceUrls: [
      "Research/starter-pack-product-reset-2026-03-09.md",
      "starter-pack/README.md",
      "starter-pack/APPLY.md",
    ],
    installHint: "Use as the default orchestration skill for this project track before assigning parallel tasks.",
    localPath: "skills/starter-pack-work-split/SKILL.md",
  },
  {
    id: "codex-claude-handoff",
    label: "Codex Claude Handoff",
    summary: "Project-owned workflow for parallel Codex + Claude Code execution across projects. Adds project-relevance checks, long-leg delegation packets, model-based routing, and strict handoff evidence.",
    tags: ["handoff", "parallel", "codex", "claude-code", "routing", "worktrees"],
    recommendedWhen: ["parallel agent work", "cross-project context risk", "reducing user interruptions during delegation"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/codex-claude-handoff/SKILL.md",
    evidenceUrls: [
      "https://developers.openai.com/codex",
      "https://docs.anthropic.com/en/docs/claude-code",
      "https://github.com/obra/superpowers",
    ],
    installHint: "Already part of this repo. Use for task routing and handoff before parallel execution starts.",
    localPath: "skills/codex-claude-handoff/SKILL.md",
  },
  {
    id: "agent-baseline-onboarding",
    label: "Agent Baseline Onboarding",
    summary: "Project-owned workflow for turning fresh-machine setup research into a small stable baseline for Codex and Claude Code without overconfiguring either tool.",
    tags: ["baseline", "onboarding", "claude-code", "codex", "mcp", "skills", "setup"],
    recommendedWhen: ["setting up a fresh machine", "rebuilding tool baseline", "turning research into install steps"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/agent-baseline-onboarding/SKILL.md",
    evidenceUrls: [
      "https://docs.anthropic.com/en/docs/claude-code",
      "https://developers.openai.com/codex",
      "https://github.com/obra/superpowers",
    ],
    installHint: "Already part of this repo. Use it to apply the smallest stable baseline first, then stage higher-risk additions separately.",
    localPath: "skills/agent-baseline-onboarding/SKILL.md",
  },
  {
    id: "source-onboarding",
    label: "Source Onboarding",
    summary: "Project-owned workflow for adding a new trusted source, fixture, and config entry to Signal Scout without breaking the ingestion pipeline.",
    tags: ["source", "ingestion", "telegram", "github", "fixtures", "trusted-sources"],
    recommendedWhen: ["adding a new source", "wiring a new Telegram channel", "expanding watchlists"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/source-onboarding/SKILL.md",
    evidenceUrls: [
      "https://github.com/vercel-labs/skills",
      "https://github.com/openai/skills",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/source-onboarding/SKILL.md",
  },
  {
    id: "digest-review",
    label: "Digest Review",
    summary: "Project-owned workflow for auditing a generated digest, checking ranking quality, actionability, and false positives.",
    tags: ["digest", "ranking", "analysis", "review", "quality"],
    recommendedWhen: ["digest quality looks off", "too much hype", "need a faster executive summary"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/digest-review/SKILL.md",
    evidenceUrls: [
      "https://vercel.com/blog/agents-md-outperforms-skills-in-our-agent-evals",
      "https://docs.anthropic.com/en/docs/claude-code/best-practices",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/digest-review/SKILL.md",
  },
  {
    id: "community-research",
    label: "Community Research",
    summary: "Project-owned workflow for turning practitioner chatter, repos, and OSS signals into structured evidence instead of vague hype.",
    tags: ["community", "oss", "research", "adoption", "signals"],
    recommendedWhen: ["official guidance feels incomplete", "need practice truth", "want stronger community evidence"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/community-research/SKILL.md",
    evidenceUrls: [
      "https://github.com/obra/superpowers",
      "https://www.lennysnewsletter.com/p/head-of-claude-code-what-happens",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/community-research/SKILL.md",
  },
  {
    id: "deep-research",
    label: "Deep Research",
    summary: "Project-owned workflow for comparison passes that separate official truth from field evidence, dedupe repeated claims, and end with an adopt / experiment / watch / reject decision.",
    tags: ["deep-research", "research", "comparison", "synthesis", "decision"],
    recommendedWhen: ["doing deep research", "comparing multiple reports or ecosystems", "running a synthesis memo before a decision"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/deep-research/SKILL.md",
    evidenceUrls: [
      "Research/radar-presets-deep-research-2026-03-11.md",
      "Research/radar-preset-implementation-pass-2026-03-11.md",
      "https://github.com/obra/superpowers",
    ],
    installHint: "Already part of this repo. Use when the task needs a real synthesis pass, not a quick lookup.",
    localPath: "skills/deep-research/SKILL.md",
  },
  {
    id: "code-review",
    label: "Code Review",
    summary: "Project-owned review workflow for finding bugs, regressions, weak assumptions, and missing verification before we call an implementation done.",
    tags: ["code-review", "review", "regression", "bugs", "verification"],
    recommendedWhen: ["reviewing a pass", "checking a diff", "looking for regressions", "verifying whether a code change is actually safe"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/code-review/SKILL.md",
    evidenceUrls: [
      "Research/radar-presets-deep-research-2026-03-11.md",
      "Research/github-adoption-signal-review-2026-03-09.md",
      "https://docs.anthropic.com/en/docs/claude-code/best-practices",
    ],
    installHint: "Already part of this repo. Use when there is code to inspect and the real question is whether the pass is safe and complete.",
    localPath: "skills/code-review/SKILL.md",
  },
  {
    id: "copywriting",
    label: "Copywriting",
    summary: "Project-owned workflow for sharpening messaging, positioning, headlines, CTAs, creator hooks, and business-facing copy when the weakness is wording rather than code.",
    tags: ["copywriting", "website", "creator", "business", "cta", "messaging"],
    recommendedWhen: ["improving website copy", "tightening a landing page", "fixing weak CTA or headline", "sharpening creator or business messaging"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/copywriting/SKILL.md",
    evidenceUrls: [
      "Research/copywriting-skill-pass-2026-03-11.md",
      "https://gist.github.com/boringmarketer/96192770df22ac2a9ff4aed72b4c20f4",
      "https://skillstore.io/skills/coreyhaines31-copywriting",
    ],
    installHint: "Already part of this repo. Use when website, creator, or business output is weak because the message is unclear, not because implementation is missing.",
    localPath: "skills/copywriting/SKILL.md",
  },
  {
    id: "design-audit-readonly",
    label: "Design Audit Readonly",
    summary: "Project-owned read-only workflow for auditing app/web UI quality against modern design and accessibility best practices without changing application code.",
    tags: ["design", "ui", "ux", "audit", "accessibility", "read-only", "frontend"],
    recommendedWhen: ["need best-practices design audit", "want prioritized UI issues", "must avoid direct code edits during review"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "project-owned",
    sourceUrl: "skills/design-audit-readonly/SKILL.md",
    evidenceUrls: [
      "Research/radar-presets-deep-research-2026-03-11.md",
      "https://www.w3.org/WAI/WCAG22/quickref/",
    ],
    installHint: "Use for strict read-only UI audits. Promote to adopt-now after repeated successful passes on real app flows.",
    localPath: "skills/design-audit-readonly/SKILL.md",
  },
  {
    id: "ui-qa-autopilot",
    label: "UI QA Autopilot",
    summary: "Project-owned browser QA workflow for automated click-through of safe UI flows with reproducible evidence and severity-ranked findings.",
    tags: ["ui", "qa", "automation", "playwright", "browser", "testing", "frontend"],
    recommendedWhen: ["manual click testing is too slow", "need automated UI interaction checks", "want screenshot-backed QA findings"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "project-owned",
    sourceUrl: "skills/ui-qa-autopilot/SKILL.md",
    evidenceUrls: [
      "Research/starter-pack-monitoring-signal-question-2026-03-11.md",
      "https://playwright.dev/docs/best-practices",
    ],
    installHint: "Use for repeated browser QA loops. Keep destructive actions blocked unless the task explicitly allows them.",
    localPath: "skills/ui-qa-autopilot/SKILL.md",
  },
  {
    id: "skill-lookup",
    label: "Skill Lookup",
    summary: "Project-owned workflow for answering whether a skill, repo pattern, or trusted-source recommendation already exists for a task before inventing a new one.",
    tags: ["lookup", "skills", "catalog", "workflow", "reuse"],
    recommendedWhen: ["asking if a skill already exists", "starting a new task", "wanting a baseline before coding"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/skill-lookup/SKILL.md",
    evidenceUrls: [
      "https://github.com/vercel-labs/skills",
      "https://developers.openai.com/codex/prompting-guide/#creating-custom-skills",
      "https://docs.anthropic.com/en/docs/claude-code/skills",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/skill-lookup/SKILL.md",
  },
  {
    id: "systematic-debugging",
    label: "Systematic Debugging",
    summary: "Project-owned debugging workflow that forces root-cause isolation instead of random edits. Adapted from obra/superpowers with Signal Scout-specific verification commands.",
    tags: ["debugging", "root-cause", "reliability", "quality"],
    recommendedWhen: ["bug is unclear", "fix keeps failing", "need to stop guessing"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/systematic-debugging/SKILL.md",
    evidenceUrls: [
      "https://github.com/obra/superpowers",
      "https://skills.sh/",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/systematic-debugging/SKILL.md",
  },
  {
    id: "verification-before-completion",
    label: "Verification Before Completion",
    summary: "Project-owned quality gate that forces proof before declaring a task done. Includes Signal Scout-specific verification commands for tests, digest, lookup, and sync. Adapted from obra/superpowers.",
    tags: ["verification", "quality", "done-criteria", "testing"],
    recommendedWhen: ["agent says it is done", "need stronger completion checks", "want fewer false-successes"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/verification-before-completion/SKILL.md",
    evidenceUrls: [
      "https://github.com/obra/superpowers",
      "https://skills.sh/",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/verification-before-completion/SKILL.md",
  },
  {
    id: "using-git-worktrees",
    label: "Using Git Worktrees",
    summary: "Project-owned branch-isolation workflow for parallel agent work. Covers setup, verification, cleanup, and integration notes for both Claude Code and Codex. Adapted from obra/superpowers.",
    tags: ["git", "worktrees", "parallel", "branches", "isolation"],
    recommendedWhen: ["parallel work", "agent branch isolation", "larger refactors"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "project-owned",
    sourceUrl: "skills/using-git-worktrees/SKILL.md",
    evidenceUrls: [
      "https://github.com/obra/superpowers",
      "https://skills.sh/",
      "https://www.lennysnewsletter.com/p/head-of-claude-code-what-happens",
    ],
    installHint: "Already part of this repo. Sync into agent-specific folders with npm run sync:agents.",
    localPath: "skills/using-git-worktrees/SKILL.md",
  },
  {
    id: "test-driven-development",
    label: "Test Driven Development",
    summary: "A strict red-green-refactor workflow that is especially valuable for long-running or autonomous agent work.",
    tags: ["testing", "tdd", "quality", "red-green-refactor"],
    recommendedWhen: ["agent starts changing behavior", "need safer refactors", "want tighter eval-like feedback"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/obra/superpowers",
    evidenceUrls: [
      "https://github.com/obra/superpowers",
      "https://skills.sh/",
    ],
    installHint: "Prefer selective adoption. Great for implementation sessions, not every trivial edit.",
  },
  {
    id: "find-skills",
    label: "Find Skills",
    summary: "A meta-skill and ecosystem tool for discovering installable skills before building a custom one from scratch.",
    tags: ["discovery", "catalog", "ecosystem", "search"],
    recommendedWhen: ["before creating a new skill", "searching the ecosystem", "checking if a workflow already exists"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/vercel-labs/skills",
    evidenceUrls: [
      "https://github.com/vercel-labs/skills",
      "https://skills.sh/",
    ],
    installHint: "Use the open skills ecosystem as the first discovery pass, then install only the few skills that matter.",
  },
  {
    id: "react-best-practices",
    label: "React Best Practices",
    summary: "A reusable frontend skill pattern for React and Next.js work, useful when Volcker Copilot or adjacent frontend tasks resurface.",
    tags: ["react", "next.js", "frontend", "typescript", "vercel"],
    recommendedWhen: ["touching React code", "starting a Next.js page", "reviewing frontend architecture"],
    compatibility: ["codex", "claude-code"],
    maturity: "watch",
    sourceClass: "community",
    sourceUrl: "https://github.com/vercel-labs/agent-skills",
    evidenceUrls: [
      "https://github.com/vercel-labs/skills",
      "https://github.com/vercel-labs/agent-skills",
    ],
    installHint: "Keep on the shortlist. Pull it in when frontend work is active rather than by default.",
  },
  {
    id: "mcp-cli",
    label: "MCP CLI",
    summary: "Experimental skill for using MCP servers on demand without preloading them into the session context.",
    tags: ["mcp", "cli", "experimental", "tooling"],
    recommendedWhen: ["exploring MCP servers", "trying tools without permanent setup", "one-off MCP tasks"],
    compatibility: ["claude-code"],
    maturity: "experiment",
    sourceClass: "community",
    sourceUrl: "https://github.com/obra/superpowers-lab",
    evidenceUrls: [
      "https://github.com/obra/superpowers-lab",
      "https://github.com/anthropics/skills",
    ],
    installHint: "Treat as lab material. Useful to watch, but not part of the default baseline yet.",
  },
  {
    id: "playwright",
    label: "Playwright",
    summary: "Browser automation workflow for navigation, form filling, snapshots, screenshots, extraction, and UI-flow debugging. Now baseline-relevant for website and creator output paths.",
    tags: ["browser", "playwright", "ui", "frontend", "qa", "creator"],
    recommendedWhen: ["checking live websites", "reviewing UI changes", "validating browser flows", "creator or web output needs real browser evidence"],
    compatibility: ["codex"],
    maturity: "adopt-now",
    sourceClass: "official",
    sourceUrl: "C:/Users/MI/.codex/skills/playwright/SKILL.md",
    evidenceUrls: [
      "Research/starter-pack-monitoring-signal-question-2026-03-11.md",
      "Research/radar-presets-deep-research-2026-03-11.md",
    ],
    installHint: "Already available in the local Codex environment. Treat as a first-class workflow for website and creator use-cases.",
    localPath: "C:/Users/MI/.codex/skills/playwright/SKILL.md",
  },
  {
    id: "vercel-deploy",
    label: "Vercel Deploy",
    summary: "Deploy workflow for shipping previews and live links. Important because publish loops proved beginner-relevant earlier than expected.",
    tags: ["deploy", "vercel", "preview", "website", "creator"],
    recommendedWhen: ["shipping websites", "publishing a first project", "validating a deploy loop", "sharing a live preview"],
    compatibility: ["codex"],
    maturity: "adopt-now",
    sourceClass: "official",
    sourceUrl: "C:/Users/MI/.codex/skills/vercel-deploy/SKILL.md",
    evidenceUrls: [
      "Research/starter-pack-monitoring-signal-question-2026-03-11.md",
      "Research/radar-presets-deep-research-2026-03-11.md",
    ],
    installHint: "Already available in the local Codex environment. Promote it whenever the output needs a real URL, not just code on disk.",
    localPath: "C:/Users/MI/.codex/skills/vercel-deploy/SKILL.md",
  },
  {
    id: "slides",
    label: "Slides",
    summary: "System skill for building and editing presentation decks. Strong evidence that presentations deserve explicit product and catalog coverage.",
    tags: ["slides", "presentations", "decks", "storytelling", "creator", "business"],
    recommendedWhen: ["making a presentation", "turning research into a deck", "building creator or business outputs"],
    compatibility: ["codex"],
    maturity: "adopt-now",
    sourceClass: "official",
    sourceUrl: "C:/Users/MI/.codex/skills/.system/slides/SKILL.md",
    evidenceUrls: [
      "Research/starter-pack-monitoring-signal-question-2026-03-11.md",
      "Research/radar-presets-deep-research-2026-03-11.md",
    ],
    installHint: "Already available in the local Codex environment. Treat presentations as a real output category, not a side case.",
    localPath: "C:/Users/MI/.codex/skills/.system/slides/SKILL.md",
  },
  {
    id: "spreadsheets",
    label: "Spreadsheets",
    summary: "System skill for workbook-style outputs. Especially relevant for business, sports, and reporting-oriented preset lenses.",
    tags: ["spreadsheets", "reporting", "dashboards", "business", "sports"],
    recommendedWhen: ["building lightweight dashboards", "tracking metrics", "supporting presentation or business workflows"],
    compatibility: ["codex"],
    maturity: "experiment",
    sourceClass: "official",
    sourceUrl: "C:/Users/MI/.codex/skills/.system/spreadsheets/SKILL.md",
    evidenceUrls: [
      "Research/radar-presets-deep-research-2026-03-11.md",
    ],
    installHint: "Use selectively. Strong candidate for business and sports overlays, but not part of the universal beginner floor.",
    localPath: "C:/Users/MI/.codex/skills/.system/spreadsheets/SKILL.md",
  },
  {
    id: "screenshot",
    label: "Screenshot",
    summary: "OS-level screenshot capture workflow that supports visual review, presentation QA, and creator/browser evidence capture.",
    tags: ["screenshot", "visual", "review", "presentations", "creator", "browser"],
    recommendedWhen: ["capturing UI evidence", "reviewing visual output", "building presentations from live screens"],
    compatibility: ["codex"],
    maturity: "experiment",
    sourceClass: "official",
    sourceUrl: "C:/Users/MI/.codex/skills/screenshot/SKILL.md",
    evidenceUrls: [
      "Research/radar-presets-deep-research-2026-03-11.md",
    ],
    installHint: "Useful when visual proof matters, but keep it as a supporting tool rather than a default recommendation.",
    localPath: "C:/Users/MI/.codex/skills/screenshot/SKILL.md",
  },
  {
    id: "frontend-design",
    label: "Frontend Design",
    summary: "Instructs Claude to commit to a bold aesthetic direction ג€” distinctive typography, cohesive color system, meaningful motion ג€” before writing frontend code. Kills generic AI slop aesthetics.",
    tags: ["frontend", "design", "ui", "css", "typography", "website", "creator"],
    recommendedWhen: ["building a web page", "creating UI components", "starting any frontend work", "need distinctive visual direction"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "official",
    sourceUrl: "https://github.com/anthropics/claude-code-skills",
    evidenceUrls: [
      "https://github.com/alenazaharovaux/share/tree/main/skills/frontend-design",
      "https://github.com/anthropics/claude-code-skills",
    ],
    installHint: "Official Anthropic plugin (Apache 2.0). Should be part of every websites-profile baseline.",
    localPath: "skills/frontend-design/SKILL.md",
  },
  {
    id: "design-elevation",
    label: "Design Elevation",
    summary: "Project-owned refinement skill for taking a working website, app, dashboard, or presentation beyond the generic first draft. Adds a deliberate polish loop, design interrogation, reference-driven direction choice, and restraint checks.",
    tags: ["design", "polish", "frontend", "presentation", "dashboard", "ui", "ux", "refinement"],
    recommendedWhen: ["a visual output works but feels generic", "polishing a site before finalizing it", "elevating a dashboard or presentation", "showing before-and-after design improvement"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "project-owned",
    sourceUrl: "skills/design-elevation/SKILL.md",
    evidenceUrls: [
      "https://claude.com/resources/use-cases/elevate-claudes-design-using-skills",
      "skills/frontend-design/SKILL.md",
      "C:/Users/MI/.codex/skills/web-design-guidelines/SKILL.md",
    ],
    installHint: "Use after the first functional pass. Pair it with frontend-design for direction-setting and web-design-guidelines for usability guardrails.",
    localPath: "skills/design-elevation/SKILL.md",
  },
  {
    id: "frontend-slides",
    label: "Frontend Slides",
    summary: "Zero-dependency HTML slide decks with animations and 12 aesthetic presets. Every slide fits exactly one screen. Can convert PowerPoint files. Show-don't-tell style discovery for non-designers.",
    tags: ["slides", "presentations", "html", "frontend", "creator", "website"],
    recommendedWhen: ["making a web presentation", "converting PowerPoint to HTML", "creating pitch decks", "need browser-native slides"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/frontend-slides",
    evidenceUrls: [
      "https://github.com/alenazaharovaux/share",
    ],
    installHint: "MIT license. Complements the Codex-only slides skill by working in Claude Code too.",
    localPath: "skills/frontend-slides/SKILL.md",
  },
  {
    id: "ux-audit",
    label: "UX Audit",
    summary: "50-item UX audit across 5 blocks (Nielsen heuristics, conversion, content, technical, IA). Prioritized report with safeguards against hallucinated stats and inflated severity. Stress-tested 12/12.",
    tags: ["ux", "audit", "website", "conversion", "accessibility", "frontend", "design"],
    recommendedWhen: ["reviewing a website", "checking landing page quality", "evaluating usability", "assessing conversion", "auditing UX"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/ux-audit",
    evidenceUrls: [
      "https://github.com/alenazaharovaux/share",
    ],
    installHint: "MIT license. More structured and stress-tested than the project-owned design-audit-readonly. Consider promoting as the primary UX audit skill.",
    localPath: "skills/ux-audit/SKILL.md",
  },
  {
    id: "visual-explainer",
    label: "Visual Explainer",
    summary: "Generates styled HTML pages for architecture diagrams, data tables, timelines, dashboards, and investigation maps. Never falls back to ASCII art. Supports Mermaid, Chart.js, and distinctive typography.",
    tags: ["visualization", "diagrams", "html", "mermaid", "dashboard", "frontend", "website"],
    recommendedWhen: ["need visual diagrams", "building architecture views", "creating data tables", "making dashboards", "any structured visualization"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/visual-explainer",
    evidenceUrls: [
      "https://github.com/nicobailon/visual-explainer",
      "https://github.com/alenazaharovaux/share",
    ],
    installHint: "MIT license. Adapted from nicobailon/visual-explainer with extended journalism and research design patterns. Fills a gap ג€” no existing visualization skill in the catalog.",
    localPath: "skills/visual-explainer/SKILL.md",
  },
  {
    id: "skill-stress-test",
    label: "Skill Stress Test",
    summary: "TDD applied to skill documentation. RED-GREEN-REFACTOR cycle for writing, testing, and bulletproofing skills against agent rationalization under pressure.",
    tags: ["skill-quality", "tdd", "testing", "rationalization", "pressure-scenarios"],
    recommendedWhen: ["creating a new skill", "editing an existing skill", "verifying skill quality before deployment"],
    compatibility: ["claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/skill-stress-test",
    evidenceUrls: ["https://github.com/alenazaharovaux/share"],
    localPath: "skills/skill-stress-test/SKILL.md",
  },
  {
    id: "tool-scout",
    label: "Tool Scout",
    summary: "Search 5 sources (web, GitHub, MCP catalogs, awesome-lists, package registries) to find existing tools before building from scratch. Adaptive source selection by task type.",
    tags: ["tool-discovery", "search", "mcp", "github", "awesome-lists", "libraries"],
    recommendedWhen: ["looking for tools or services to solve a task", "checking if an MCP server exists", "finding libraries before writing code"],
    compatibility: ["claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/tool-scout",
    evidenceUrls: ["https://github.com/alenazaharovaux/share"],
    localPath: "skills/tool-scout/SKILL.md",
  },
  {
    id: "triage-finding",
    label: "Triage Finding",
    summary: "Assess external findings (posts, links, videos, screenshots) ג€” explain in plain language, map to current projects, recommend action (apply now / save / skip). Includes fact-checking and ideas folder review.",
    tags: ["triage", "findings", "links", "telegram", "youtube", "ideas", "project-mapping"],
    recommendedWhen: ["user shares a link or post to evaluate", "triaging Telegram or Reddit findings", "reviewing saved ideas folder"],
    compatibility: ["claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/triage-finding",
    evidenceUrls: ["https://github.com/alenazaharovaux/share"],
    localPath: "skills/triage-finding/SKILL.md",
  },
  {
    id: "brainstorming",
    label: "Brainstorming",
    summary: "Structured idea-to-design workflow. Explores context, proposes 2-3 approaches, presents design sections, writes design doc. Hard gate: no implementation without design sign-off.",
    tags: ["design", "ideation", "planning", "approval", "gate"],
    recommendedWhen: ["starting a new feature or project", "exploring design options before coding", "need structured idea exploration"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/obra/superpowers",
    evidenceUrls: ["https://github.com/obra/superpowers", "https://github.com/alenazaharovaux/share"],
  },
  {
    id: "writing-plans",
    label: "Writing Plans",
    summary: "Break large work into small verifiable steps with clear done criteria, risks, and checks. Produces sequenced implementation plans.",
    tags: ["planning", "sequencing", "steps", "verification", "architecture"],
    recommendedWhen: ["work is large enough to need sequencing", "need verifiable steps with done criteria", "planning multi-step implementation"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/obra/superpowers",
    evidenceUrls: ["https://github.com/obra/superpowers"],
  },
  {
    id: "executing-plans",
    label: "Executing Plans",
    summary: "Execute implementation plans one step at a time. Verify each step before proceeding. Replan when evidence changes.",
    tags: ["execution", "plans", "verification", "step-by-step", "replan"],
    recommendedWhen: ["a plan exists and needs execution", "implementing step-by-step with verification", "need disciplined plan execution"],
    compatibility: ["codex", "claude-code"],
    maturity: "adopt-now",
    sourceClass: "community",
    sourceUrl: "https://github.com/obra/superpowers",
    evidenceUrls: ["https://github.com/obra/superpowers"],
  },
  {
    id: "adr",
    label: "Architecture Decision Records",
    summary: "Log architecture decisions (what, why, what was rejected) in one Markdown file per project. ~1 min per entry. Includes retroactive and draft modes.",
    tags: ["architecture", "decisions", "documentation", "adr", "context", "dotnotes"],
    recommendedWhen: ["making a decision you need to remember in 6 months", "documenting why a specific approach was chosen", "onboarding new contributors who need architectural context"],
    compatibility: ["claude-code"],
    maturity: "watch",
    sourceClass: "community",
    sourceUrl: "https://github.com/alenazaharovaux/share/tree/main/skills/adr",
    evidenceUrls: ["https://github.com/alenazaharovaux/share", "OpenAI Build Hour 2026-03 (Basis dotnotes pattern)"],
  },
  {
    id: "agent-legibility-scorecard",
    label: "Agent Legibility Scorecard",
    summary: "Grade how agentic-ready a repository is across 7 dimensions: bootstrap, task entrypoints, validation harness, lint gates, agent repo map, structured docs, decision records.",
    tags: ["agent-readiness", "repo-scoring", "harness-engineering", "legibility", "evaluation"],
    recommendedWhen: ["evaluating a new repo for agent workflow adoption", "auditing project setup for agentic readiness", "comparing repos on GitHub watchlist"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "community",
    sourceUrl: "https://openai.com/index/harness-engineering/",
    evidenceUrls: [
      "https://openai.com/index/harness-engineering/",
      "https://vercel.com/blog/agents-md-outperforms-skills-in-our-agent-evals",
      "https://github.blog/ai-and-ml/github-copilot/how-to-write-a-great-agents-md-lessons-from-over-2500-repositories/",
      "https://arxiv.org/html/2602.11988v1",
      "https://martinfowler.com/articles/exploring-gen-ai/harness-engineering.html",
    ],
  },
  {
    id: "archgate-cli",
    label: "Archgate CLI",
    summary: "Executable architecture decision records with .rules.ts companions. Runs in CI, pre-commit hooks, and exposes an MCP server for agents to read ADRs before writing code. Has Claude Code plugin.",
    tags: ["adr", "architecture", "linting", "mcp", "ci", "harness-engineering"],
    recommendedWhen: ["enforcing architectural rules mechanically", "giving agents access to ADRs via MCP", "automating architecture compliance in CI"],
    compatibility: ["codex", "claude-code"],
    maturity: "experiment",
    sourceClass: "community",
    sourceUrl: "https://github.com/archgate/cli",
    evidenceUrls: [
      "https://github.com/archgate/cli",
      "https://martinfowler.com/articles/exploring-gen-ai/harness-engineering.html",
    ],
  },
  {
    id: "agent-decision-record",
    label: "Agent Decision Record (AgDR)",
    summary: "Structured decision log format extending ADR for AI agent decisions. Addresses invisible decisions, lost context, and unauditable PRs from agent-generated code.",
    tags: ["adr", "decisions", "audit", "dotnotes", "agent-transparency"],
    recommendedWhen: ["tracking non-obvious agent decisions", "auditing agent-generated PRs", "building reasoning trails for agent sessions"],
    compatibility: ["codex", "claude-code"],
    maturity: "watch",
    sourceClass: "community",
    sourceUrl: "https://github.com/me2resh/agent-decision-record",
    evidenceUrls: [
      "https://github.com/me2resh/agent-decision-record",
      "https://openai.com/index/harness-engineering/",
    ],
  },
];





